# Generated by Django 3.1.4 on 2022-10-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=30)),
                ('housename', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='meat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('price_kg', models.CharField(db_column='price/kg', max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=50)),
                ('MEAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.meat')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=25)),
                ('house_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('pin_code', models.IntegerField(db_column='pin code')),
                ('email', models.CharField(max_length=25)),
                ('phone_no', models.CharField(db_column='phone no', max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('MEAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.meat')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode_of_payment', models.CharField(max_length=25)),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='deliverystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('DELIVERY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deliveryboy')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
