# Generated by Django 3.1.4 on 2022-10-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='MEAT',
        ),
    ]
