# Generated by Django 3.1.4 on 2022-10-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20221030_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystatus',
            name='DELIVERY',
        ),
        migrations.RemoveField(
            model_name='deliverystatus',
            name='ORDER',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ORDER',
        ),
        migrations.RemoveField(
            model_name='order',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ORDER',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='deliverystatus',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
