# Generated by Django 3.1.4 on 2022-10-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20221030_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('quantity', models.CharField(max_length=50)),
                ('STOCK', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.stock')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode_of_payment', models.CharField(max_length=25)),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='deliverystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('DELIVERY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deliveryboy')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
    ]
