# Generated by Django 3.1.4 on 2022-10-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='feedback',
            field=models.CharField(default='pending', max_length=150),
        ),
    ]
