# Generated by Django 3.2.15 on 2022-11-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_order_main_order_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_main',
            name='order_sub',
        ),
        migrations.AddField(
            model_name='order_main',
            name='date',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
