# Generated by Django 3.2.14 on 2022-11-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20221104_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='feedback',
            new_name='reciept',
        ),
    ]
