# Generated by Django 3.2.14 on 2022-11-07 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_feedback_payment_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_sub',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_main'),
        ),
    ]
