# Generated by Django 3.2.14 on 2022-11-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_order_sub_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='feedback',
            field=models.CharField(default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reciept',
            field=models.CharField(max_length=150),
        ),
    ]
