# Generated by Django 3.2.14 on 2022-11-08 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_deliverystatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ORDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_main'),
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
