# Generated by Django 3.2.14 on 2022-11-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_order_main_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_sub',
            name='qty',
            field=models.IntegerField(max_length=50),
        ),
    ]
