# Generated by Django 3.2.14 on 2022-11-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_order_sub_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='price_kg',
            field=models.IntegerField(db_column='price/kg', max_length=50),
        ),
    ]
